import { Book } from './book';

export const BOOK : Book[] = [
    {id: 1, 
     title: 'Diary of a Wimpy Kid: Hard Luck ',
     author:"Jeff Kinney",
     description:'Diary of A Wimpy Kid: Hard Luck is the 8th edition of this beautifully scripted children-specific series. Greg Heffley is on an uninterrupted series of losing in life. Rowley Jefferson, who is his best pal, has dumped him for his new girlfriend, Abigail. Greg is now struggling to make new friends in mid-school. Rowley deems that Greg is jealous.',
     category:"fiction"
    },
    {id: 2, title: 'Diary of a Wimpy Kid: Dog Days',
    author:"Jeff Kinney",
    description:'Diary of a Wimpy Kid: Dog Days is the super funny fourth title in the highly-illustrated, bestselling and award-winning Diary of a Wimpy Kid series by Jeff Kinney. Perfect for both boys and girls of 8+, reluctant readers and all the millions of devoted Wimpy Kid fans out there. Dog Days is also a major motion picture and box office smash.',
    category:"fiction"},
    {id: 3, 
    title: 'Diary of a Wimpy Kid: The Third Wheel',
    author:"Jeff Kinney",
    description:'The Third Wheel is the hilarious new book in the brilliant, bestselling and award-winning Diary of a Wimpy Kid series. Perfect for readers of 8+ and all the millions of Wimpy Kid fans. Also now a box office-busting major motion franchise with the third Wimpy Kid movie, Dog Days released in the UK in August 2012!',
    category:"fiction"},

    {id: 4, 
      title: 'English Grammar',
      author:"Madhuban",
      description:'English Grammar for grade 2',
      category:"school"},
    {id: 5, 
      title: 'Maths',
      author:"Madhuban",
      description:'Maths for grade 2',
      category:"school"},
    {id: 6, 
      title: 'Social Science',
      author:"Madhuban",
      description:'Social Science for grade 2',
      category:"school"},

    {id: 7, 
      title: 'Lingaashtakam',
      author:"author 1",
      description:'Lingaashtakam',
      category:"spiritual"},
    {id: 8, 
      title: 'Spiritual Speech by GR',
      author:"GR",
      description:'Spiritual Speech by GR',
      category:"spiritual"},
   ];